version: '3'
services:
  web:
    container_name: web
    image: nginx:1.17.9-alpine
    ports:
      - "8080:80"
    volumes:
      - ./vhosts.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www
    networks:
      - mynetwork
  php:
    container_name: php
    image: php:7.4.4-fpm
    volumes:
      - ./:/var/www
    environment:
      - APP_ENV="development"
    networks:
      - mynetwork
networks:
  mynetwork: